In [31]:
function  prolongation1(n)
    r = ceil(n/2) 
    R = zeros(r,n)
    i = 1
    j = 1
    while i <= r 
        R[i,j] = 1
        i = i + 1
        j = j + 2
    end
    return R
end

prolongation1 (generic function with 1 method)

In [32]:
prolongation1(14)

7×14 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0

In [42]:
prolongation1(15)

8×15 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [33]:
function  prolongation2(n)
    r = ceil(n/2)
    R = zeros(r,n)
    i = 1
    j = 1
    while i <= r 
        R[i,j] = 1
        if(j+1 <= n)
            R[i,j+1] = 2
        end
        if(j+2 <= n)
            R[i,j+2] = 1
        end
        i = i + 1
        j = j + 2
    end
    return 1/4*R
end

prolongation2 (generic function with 1 method)

In [44]:
prolongation2(14)

7×14 Array{Float64,2}:
 0.25  0.5  0.25  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0
 0.0   0.0  0.25  0.5  0.25  0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0
 0.0   0.0  0.0   0.0  0.25  0.5  0.25  0.0  0.0   0.0  0.0   0.0  0.0   0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.25  0.5  0.25  0.0  0.0   0.0  0.0   0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.25  0.5  0.25  0.0  0.0   0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.25  0.5  0.25  0.0
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.0   0.0  0.25  0.5

In [43]:
prolongation2(15)

8×15 Array{Float64,2}:
 0.25  0.5  0.25  0.0  0.0   0.0  0.0   …  0.0  0.0   0.0  0.0   0.0  0.0 
 0.0   0.0  0.25  0.5  0.25  0.0  0.0      0.0  0.0   0.0  0.0   0.0  0.0 
 0.0   0.0  0.0   0.0  0.25  0.5  0.25     0.0  0.0   0.0  0.0   0.0  0.0 
 0.0   0.0  0.0   0.0  0.0   0.0  0.25     0.0  0.0   0.0  0.0   0.0  0.0 
 0.0   0.0  0.0   0.0  0.0   0.0  0.0      0.5  0.25  0.0  0.0   0.0  0.0 
 0.0   0.0  0.0   0.0  0.0   0.0  0.0   …  0.0  0.25  0.5  0.25  0.0  0.0 
 0.0   0.0  0.0   0.0  0.0   0.0  0.0      0.0  0.0   0.0  0.25  0.5  0.25
 0.0   0.0  0.0   0.0  0.0   0.0  0.0      0.0  0.0   0.0  0.0   0.0  0.25

In [37]:
# Solves the System Ax=b with de Deflation-Operator R
function solve(A, b, R)
    # Compute A = M - N
    n= size(A,1)
    x = ones(n)
    
    M = Diagonal(A)
    M1 = M^(-1)
    N = M - A
    
    I = eye(n)
    S = I - M1*A
    P = transpose(R)
    PAR = (P*(R*A*P)^(-1)*R)
    T = S * (I - PAR) * S
    while(norm(b-A*x)>0.1)
        x = (M1 * N * x) + (M1 * b)
        x = T*x + PAR*b
    end
    x
end

solve (generic function with 1 method)

In [41]:
A = [1. 2. 3.; 1. 2. 3.; 1. 2. 3.]
solve(A, [1.;1.;1.], prolongation1(size(A,1)))

LoadError: Base.LinAlg.SingularException(2)